#!/bin/bash

# Copyright (C) 2013  Mattias Andrée (maandree@member.fsf.org)
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.  [GNUAllPermissive]

cd "$(dirname "$0")"

comm -13 \
  <(cd _have_/ ; find | sort) \
  <(cd _need_/ ; find | sort) |
sed -e 's/^.\///g'

